name: Node.js Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [ 16 ]

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
        role-session-name: GitHub
        aws-region: us-east-1

    - uses: actions/checkout@v3
      with:
        fetch-depth: '1'
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build & Lint
      run: npm run build

    - name: Test
      run: |
        npm test
      env:
        AWS_REGION: us-east-1